---

- name: install sshguard
  apt:
    pkg: sshguard
    state: present
    update_cache: true
  tags: ['sshguard', 'sshguard:install']

- name: Set sshguard whitelist
  template:
    src: whitelist.j2
    dest: /etc/sshguard/whitelist
  notify: restart sshguard
  tags: ['sshguard', 'sshguard:configuration']

- name: enable sshguard systemd service
  systemd:
    name: sshguard.service
    enabled: true
  tags: ['sshguard', 'sshguard:configuration']
