---
- name: Converge
  hosts: all
  tasks:
    - name: install ansible deps
      apt:
        name:
          - virtualenv
        state: present
        update_cache: yes
    - name: "Include sshguard"
      include_role:
        name: "sshguard_role"
